// Integration derived from official Ti60F225 YOLO EVSoC Sapphire/custom-instruction wiring.
// Vendor implementations are unmodified in ignored artifacts; source hashes recorded there.
// CPU, peripheral, and memory ports use the same verified 96 MHz clock.
// Memory addresses are LOGICAL: both exported buses still need checked translation/arbitration.
module cnn_soc_subsystem #(parameter IMAGE_WIDTH=1280, IMAGE_HEIGHT=720)(
    input wire clk_96, ai_reset, ai_online,
    input wire uart_clk,uart_rst_n,
    input wire [1:0] requested,
    output wire [1:0] applied,
    output wire available,inference_enable,
    output wire system_reset,memory_reset,peripheral_reset,
    input wire pixel_clk,pixel_rst_n,
    input wire [23:0] rgb_i,
    input wire hs_i,vs_i,de_i,
    output wire [23:0] rgb_o,
    output wire hs_o,vs_o,de_o,
    output wire [31:0] displayed_source_frame,
    output wire [15:0] cpu_w_payload_strb,
    output wire [127:0] cpu_w_payload_data,
    input wire jtagCtrl_enable,
    input wire jtagCtrl_tdi,
    input wire jtagCtrl_capture,
    input wire jtagCtrl_shift,
    input wire jtagCtrl_update,
    input wire jtagCtrl_reset,
    output wire jtagCtrl_tdo,
    input wire jtagCtrl_tck,
    output wire [7:0] cpu_w_payload_id,
    input wire cpu_r_payload_last,
    input wire [1:0] cpu_r_payload_resp,
    input wire [7:0] cpu_r_payload_id,
    input wire [127:0] cpu_r_payload_data,
    output wire cpu_r_ready,
    input wire cpu_r_valid,
    input wire [1:0] cpu_b_payload_resp,
    input wire [7:0] cpu_b_payload_id,
    output wire cpu_b_ready,
    input wire cpu_b_valid,
    output wire cpu_w_payload_last,
    input wire cpu_w_ready,
    output wire cpu_w_valid,
    output wire cpu_arw_payload_write,
    output wire [2:0] cpu_arw_payload_prot,
    output wire [3:0] cpu_arw_payload_qos,
    output wire [3:0] cpu_arw_payload_cache,
    output wire cpu_arw_payload_lock,
    output wire [1:0] cpu_arw_payload_burst,
    output wire [2:0] cpu_arw_payload_size,
    output wire [7:0] cpu_arw_payload_len,
    output wire [3:0] cpu_arw_payload_region,
    output wire [7:0] cpu_arw_payload_id,
    output wire [31:0] cpu_arw_payload_addr,
    input wire cpu_arw_ready,
    output wire cpu_arw_valid,
    input wire system_spi_0_io_data_0_read,
    output wire system_spi_0_io_data_0_write,
    output wire system_spi_0_io_data_0_writeEnable,
    input wire system_spi_0_io_data_1_read,
    output wire system_spi_0_io_data_1_write,
    output wire system_spi_0_io_data_1_writeEnable,
    input wire system_spi_0_io_data_2_read,
    output wire system_spi_0_io_data_2_write,
    output wire system_spi_0_io_data_2_writeEnable,
    input wire system_spi_0_io_data_3_read,
    output wire system_spi_0_io_data_3_write,
    output wire system_spi_0_io_data_3_writeEnable,
    output wire system_spi_0_io_sclk_write,
    output wire system_uart_0_io_txd,
    input wire system_uart_0_io_rxd,
    output wire [0:0] system_spi_0_io_ss,
    output wire tiny_awvalid,
    input wire tiny_awready,
    output wire [31:0]          tiny_awaddr,
    output wire [7:0]           tiny_awlen,
    output wire [7:0]           tiny_awid,
    output wire [2:0]           tiny_awsize,
    output wire [1:0]           tiny_awburst,
    output wire [0:0]           tiny_awlock,
    output wire [3:0]           tiny_awcache,
    output wire [2:0]           tiny_awprot,
    output wire tiny_wvalid,
    input wire tiny_wready,
    output wire [127:0]   tiny_wdata,
    output wire [15:0] tiny_wstrb,
    output wire tiny_wlast,
    input wire tiny_bvalid,
    output wire tiny_bready,
    input wire [1:0]            tiny_bresp,
    output wire tiny_arvalid,
    input wire tiny_arready,
    output wire [31:0]           tiny_araddr,
    output wire [7:0]            tiny_arlen,
    output wire [7:0]            tiny_arid,
    output wire [2:0]            tiny_arsize,
    output wire [1:0]            tiny_arburst,
    output wire [0:0]            tiny_arlock,
    output wire [3:0]            tiny_arcache,
    output wire [2:0]            tiny_arprot,
    input wire tiny_rvalid,
    output wire tiny_rready,
    input wire [127:0]   tiny_rdata,
    input wire tiny_rlast,
    input wire [1:0]            tiny_rresp
);
    wire custom_cmd_valid,custom_cmd_ready,custom_irq,custom_rsp_valid,custom_rsp_ready;
    wire [9:0] custom_function;
    wire [31:0] custom_input0,custom_input1,custom_output;
    wire [15:0] PADDR;
    wire PSEL,PENABLE,PWRITE,PREADY,PSLVERROR;
    wire [31:0] PWDATA,PRDATA;
    SapphireSoc u_risc_v(
        .io_systemClk(clk_96),
        .io_peripheralClk(clk_96),
        .io_peripheralReset(peripheral_reset),
        .io_ddrA_w_payload_strb(cpu_w_payload_strb),
        .io_ddrA_w_payload_data(cpu_w_payload_data),
        .jtagCtrl_enable(jtagCtrl_enable),
        .jtagCtrl_tdi(jtagCtrl_tdi),
        .jtagCtrl_capture(jtagCtrl_capture),
        .jtagCtrl_shift(jtagCtrl_shift),
        .jtagCtrl_update(jtagCtrl_update),
        .jtagCtrl_reset(jtagCtrl_reset),
        .jtagCtrl_tdo(jtagCtrl_tdo),
        .jtagCtrl_tck(jtagCtrl_tck),
        .io_ddrA_w_payload_id(cpu_w_payload_id),
        .io_ddrA_r_payload_last(cpu_r_payload_last),
        .io_ddrA_r_payload_resp(cpu_r_payload_resp),
        .io_ddrA_r_payload_id(cpu_r_payload_id),
        .io_ddrA_r_payload_data(cpu_r_payload_data),
        .io_ddrA_r_ready(cpu_r_ready),
        .io_ddrA_r_valid(cpu_r_valid),
        .io_ddrA_b_payload_resp(cpu_b_payload_resp),
        .io_ddrA_b_payload_id(cpu_b_payload_id),
        .io_ddrA_b_ready(cpu_b_ready),
        .io_ddrA_b_valid(cpu_b_valid),
        .io_ddrA_w_payload_last(cpu_w_payload_last),
        .io_ddrA_w_ready(cpu_w_ready),
        .io_ddrA_w_valid(cpu_w_valid),
        .io_ddrA_arw_payload_write(cpu_arw_payload_write),
        .io_ddrA_arw_payload_prot(cpu_arw_payload_prot),
        .io_ddrA_arw_payload_qos(cpu_arw_payload_qos),
        .io_ddrA_arw_payload_cache(cpu_arw_payload_cache),
        .io_ddrA_arw_payload_lock(cpu_arw_payload_lock),
        .io_ddrA_arw_payload_burst(cpu_arw_payload_burst),
        .io_ddrA_arw_payload_size(cpu_arw_payload_size),
        .io_ddrA_arw_payload_len(cpu_arw_payload_len),
        .io_ddrA_arw_payload_region(cpu_arw_payload_region),
        .io_ddrA_arw_payload_id(cpu_arw_payload_id),
        .io_ddrA_arw_payload_addr(cpu_arw_payload_addr),
        .io_ddrA_arw_ready(cpu_arw_ready),
        .io_ddrA_arw_valid(cpu_arw_valid),
        .system_spi_0_io_data_0_read(system_spi_0_io_data_0_read),
        .system_spi_0_io_data_0_write(system_spi_0_io_data_0_write),
        .system_spi_0_io_data_0_writeEnable(system_spi_0_io_data_0_writeEnable),
        .system_spi_0_io_data_1_read(system_spi_0_io_data_1_read),
        .system_spi_0_io_data_1_write(system_spi_0_io_data_1_write),
        .system_spi_0_io_data_1_writeEnable(system_spi_0_io_data_1_writeEnable),
        .system_spi_0_io_data_2_read(system_spi_0_io_data_2_read),
        .system_spi_0_io_data_2_write(system_spi_0_io_data_2_write),
        .system_spi_0_io_data_2_writeEnable(system_spi_0_io_data_2_writeEnable),
        .system_spi_0_io_data_3_read(system_spi_0_io_data_3_read),
        .system_spi_0_io_data_3_write(system_spi_0_io_data_3_write),
        .system_spi_0_io_data_3_writeEnable(system_spi_0_io_data_3_writeEnable),
        .system_spi_0_io_sclk_write(system_spi_0_io_sclk_write),
        .userInterruptB(1'b0),
        .userInterruptA(custom_irq),
        .io_apbSlave_1_PADDR(PADDR),
        .io_apbSlave_1_PENABLE(PENABLE),
        .io_apbSlave_1_PRDATA(PRDATA),
        .io_apbSlave_1_PREADY(PREADY),
        .io_apbSlave_1_PSEL(PSEL),
        .io_apbSlave_1_PSLVERROR(PSLVERROR),
        .io_apbSlave_1_PWDATA(PWDATA),
        .io_apbSlave_1_PWRITE(PWRITE),
        .io_asyncReset(ai_reset),
        .io_memoryClk(clk_96),
        .io_systemReset(system_reset),
        .system_uart_0_io_txd(system_uart_0_io_txd),
        .io_memoryReset(memory_reset),
        .system_uart_0_io_rxd(system_uart_0_io_rxd),
        .cpu0_customInstruction_cmd_valid(custom_cmd_valid),
        .cpu0_customInstruction_cmd_ready(custom_cmd_ready),
        .cpu0_customInstruction_function_id(custom_function),
        .cpu0_customInstruction_inputs_0(custom_input0),
        .cpu0_customInstruction_inputs_1(custom_input1),
        .cpu0_customInstruction_rsp_valid(custom_rsp_valid),
        .cpu0_customInstruction_rsp_ready(custom_rsp_ready),
        .cpu0_customInstruction_outputs_0(custom_output),
        .system_spi_0_io_ss(system_spi_0_io_ss)
    );
    tinyml_accelerator_channels #(.AXI_DW_M(128)) u_tinyml_top_channels(
        .clk(clk_96),.reset(system_reset),
        .cmd_valid(custom_cmd_valid),.cmd_ready(custom_cmd_ready),.cmd_int(custom_irq),
        .cmd_function_id(custom_function),.cmd_inputs_0(custom_input0),.cmd_inputs_1(custom_input1),
        .rsp_valid(custom_rsp_valid),.rsp_ready(custom_rsp_ready),.rsp_outputs_0(custom_output),
        .m_axi_clk(clk_96),
        .m_axi_rstn(!system_reset),
        .m_axi_awvalid(tiny_awvalid),
        .m_axi_awready(tiny_awready),
        .m_axi_awaddr(tiny_awaddr),
        .m_axi_awlen(tiny_awlen),
        .m_axi_awid(tiny_awid),
        .m_axi_awsize(tiny_awsize),
        .m_axi_awburst(tiny_awburst),
        .m_axi_awlock(tiny_awlock),
        .m_axi_awcache(tiny_awcache),
        .m_axi_awprot(tiny_awprot),
        .m_axi_wvalid(tiny_wvalid),
        .m_axi_wready(tiny_wready),
        .m_axi_wdata(tiny_wdata),
        .m_axi_wstrb(tiny_wstrb),
        .m_axi_wlast(tiny_wlast),
        .m_axi_bvalid(tiny_bvalid),
        .m_axi_bready(tiny_bready),
        .m_axi_bresp(tiny_bresp),
        .m_axi_arvalid(tiny_arvalid),
        .m_axi_arready(tiny_arready),
        .m_axi_araddr(tiny_araddr),
        .m_axi_arlen(tiny_arlen),
        .m_axi_arid(tiny_arid),
        .m_axi_arsize(tiny_arsize),
        .m_axi_arburst(tiny_arburst),
        .m_axi_arlock(tiny_arlock),
        .m_axi_arcache(tiny_arcache),
        .m_axi_arprot(tiny_arprot),
        .m_axi_rvalid(tiny_rvalid),
        .m_axi_rready(tiny_rready),
        .m_axi_rdata(tiny_rdata),
        .m_axi_rlast(tiny_rlast),
        .m_axi_rresp(tiny_rresp)
    );
    cnn_video_endpoint #(.IMAGE_WIDTH(IMAGE_WIDTH),.IMAGE_HEIGHT(IMAGE_HEIGHT)) u_video_endpoint(
        .uart_clk(uart_clk),.uart_rst_n(uart_rst_n),.requested(requested),.applied(applied),.available(available),
        .cpu_clk(clk_96),.cpu_rst_n(!peripheral_reset),.ai_online(ai_online && !system_reset),.inference_enable(inference_enable),
        .PADDR(PADDR),.PSEL(PSEL),.PENABLE(PENABLE),.PWRITE(PWRITE),.PWDATA(PWDATA),
        .PRDATA(PRDATA),.PREADY(PREADY),.PSLVERROR(PSLVERROR),
        .pixel_clk(pixel_clk),.pixel_rst_n(pixel_rst_n),.rgb_i(rgb_i),.hs_i(hs_i),.vs_i(vs_i),.de_i(de_i),
        .rgb_o(rgb_o),.hs_o(hs_o),.vs_o(vs_o),.de_o(de_o),.displayed_source_frame(displayed_source_frame));
endmodule
